### ISSUE TITLE
Any progress on the 'dirty hack' in Index.js?

### ISSUE THREAD

**Issue by SkaterDad** [TylorS/cycle-snabbdom#1]
Hello!  I was very happy to stumble across this repo today.  I've been learning Cycle recently, but animations have been a stumbling block.  Snabbdom seems to address those nicely, so this driver is just what I was after.

In 'src/index.js', you wrote a comment about something being a hack to workaround a snabbdom bug.  Has there been any progress on fixing that?  I noticed you're using snabbdom in your Motorcycle-DOM library as well, which doesn't mention any hacks.  Is that due to using MOST instead of RxJS?

``` javascript
    const rootElem$ = view$
      .flatMapLatest(parseTree)
      .flatMap(view => {
        // dirty dirty hack to workaround snabbdom bug
        // TODO: FIX!!!!
        rootElem.innerHTML = ''
        let renderContainer = document.createElement(`div`)
        rootElem.appendChild(renderContainer)
        patch(renderContainer, view)
        return Observable.just(rootElem)
      }).replay(null, 1)
```

Even with the hack in place, would you consider this library stable and usable?

Thanks!

**Comment by TylorS** [comment]
Hello @SkaterDad, I'm glad that this library is of interest to you! To be clear when I wrote this I had very little understanding of Snabbdom, and had a great misunderstanding as to how it worked and patches the DOM. As you mentioned with my work on motorcycle-dom I've come to understand it much better and I believe that the experience I've gained there could definitely be translated back here, as it really shouldn't have anything to do with Most vs. Rx. 

I've been planning on recycling my knowledge back into this library, but just haven't gotten around to it yet. I really wouldn't call this library stable as-is because that 'hack' most likely ruins all the animations and things you're interested in using it for. With all of that said, I could probably get this into working condition by the end of the week considering it should be more or less a 1:1 port of motorcycle-dom here. If that's not acceptable, I'd gladly take a PR implementing the changes.

**Comment by TylorS** [comment]
Also I think it's worth noting that the upcoming Nested Cycle version with DOM isolation is not something I've solved for motorcycle-dom or here yet so that won't be included for at least a little while longer.

**Comment by SkaterDad** [comment]
I'll make an attempt at porting the driver tonight and will submit a PR if I can get it working & pass the tests in the library.  I'm still getting my feet wet in these libraries, but it sounds like a good learning experience.

If I can't figure it out, I'm in no rush and can wait patiently for you to find time.

**Comment by TylorS** [comment]
Check the last commit :smile:

**Comment by TylorS** [comment]
Also npm version 0.2.0 reflects the changes I just made.

**Comment by SkaterDad** [comment]
Very cool!  I look forward to try this out tonight :+1:

**Comment by TylorS** [comment]
Let me know how it works for you, as far as I know you're the only person really using this library. It's basically a 1:1 mapping of motorcycle-dom, and I also updated the dependencies etc.

**Comment by zywind** [comment]
@TylorS FYI, I will try this library too very soon once there is svg support in snabbdom (paldepind is planning to do that very soon). I think you underestimated how important this library is :). It is pretty hard to do enter and exit animation with virtual-dom, but with snabbdom, it is super easy.

**Comment by SkaterDad** [comment]
@TylorS I got this working in my project last night with minimal hiccups (just adjusting the view functions to use snabbdom's syntax).  I didn't use the hyperscript-helpers which your driver exports, just plain old 'h'.  I'll try the helpers tonight since it's so much more readable.

So far I was able to get the 'delayed' styling hook to work as planned.  The 'remove' styling hook wasn't working for me yet, but it could just be my lack of understanding snabbdom.  I'll try to isolate where the problem is by porting the snabbdom list reordering example to use cycle & this driver and seeing if the 'remove' animations still work.

**Comment by TylorS** [comment]
@zywind Cool let me know when its added you get the chance. I'll update the dependencies.

@SkaterDad glad things are working well. I wish I could help you more but I haven't really played with those aspects yet. I could be wrong, but I doubt issues regarding animations are related to this library.

**Comment by SkaterDad** [comment]
I did a rough port of the official snabbdom re-order animation example (mixed with the Cycle.js checkbox example) and it looks like the insert and remove animation hooks are working when swapping 2 sets of data.

@TylorS Are you interested in having an examples folder in this repo?  I was thinking of making an animated version of Cycle's github search example.

**Comment by TylorS** [comment]
Yeah that would be great!

**Comment by SkaterDad** [comment]
I make a couple examples and put them here: [cycle-snabbdom-examples](https://github.com/SkaterDad/cycle-snabbdom-examples).

The color changer doesn't require Snabbdom, but I wanted to evolve the usual counter example.

The Github Search example is an animated clone of the official one.

I plan to do more, but am fighting a bug related to the nested dialogue switching (routing, but using a dropdown list).  One of the dialogues has HTTP requests (the Github Search example), and starts to go nuts if you toggle examples back & forth.  [More detail on the issue page](https://github.com/SkaterDad/cycle-snabbdom-examples/issues/1).

Great work with this driver, though, it works very well!
