### ISSUE TITLE
Observable of vtrees inside a regular vtree

### ISSUE THREAD

**Issue by yemi** [TylorS/cycle-snabbdom#16]
I would like to know if it's possible to add an observable of vtrees directly into a view like in the todo-mvc example: https://github.com/cyclejs/todomvc-cycle/blob/master/src/components/Todos/view.js#L29

This looks kind of magical to me and im not sure how it works, but does cycle-snabbdom support the same kind of usage?

**Comment by SkaterDad** [comment]
@yemi  That is supported by this driver.  If I recall,  the function which parses the vTree flattens the observables.  Can't look at the source right now to double check, but that's roughly it. 

It's certainly a great feature for convenience.

**Comment by SkaterDad** [comment]
Here is a link to the section of code:  [transposition.js](https://github.com/TylorS/cycle-snabbdom/blob/master/src/transposition.js#L19-L20)

If it detects an observable, it flatMaps it and recursively calls the transpose function.

**Comment by TylorS** [comment]
Thanks @SkaterDad for pointing him to that.

**Comment by TylorS** [comment]
Closing this. If anyone feels it needs to be reopened feel free.
