### ISSUE TITLE
parseTree not handling null vTree

### ISSUE THREAD

**Issue by SkaterDad** [TylorS/cycle-snabbdom#2]
#### Description

When a null value is passed into `parseTree`, javascript thinks its typeof = 'object', so it passes this null object along to `combineVTreeStreams`.  That function gives us a runtime error since it can't check for keys on `null`.

I came across this while making my github search example fancier.  Some searches would work perfectly, but others would give this error _(funny enough, searches for "cycle" would work, but searches for "react" or "angular" would break)_.  In the end, it turned out Github's API returns `"description": null` for some repositories.  I was just putting the `description` value as a child of an `a` tag, without any other wrapping or null checks.
#### Possible updates to library code

To make debugging easier, the `parseTree` function could use a null check to throw a new error.

``` javascript
const parseTree =
  vTree => {
    // NEW CODE HERE
    if (vTree === null) {
      throw new Error(`Null tree value`)
    }
    if (vTree.observe) {
      return vTree.flatMap(parseTree)
    } else if (`object` === typeof vTree) {
      const vtree$ = Rx.Observable.just(vTree)
      if (vTree.children && vTree.children.length > 0) {
        return Rx.Observable.combineLatest(
          vtree$,
          ...map(vTree.children, parseTree),
          combineVTreeStreams
        )
      }
      return vtree$
    } else {
      throw new Error(`Unhandled tree value`)
    }
  }
```

Or it could swallow the error and convert `null` to an empty string vNode.  This is probably not ideal for a library, but for my use cases, this would work fine.  Could also post a console warning when this happens.

``` javascript
const parseTree =
  vTree => {
    // NEW CODE HERE
    if (vTree === null) {
      vTree = { text: '' }
    }
    if (vTree.observe) {
      return vTree.flatMap(parseTree)
    } else if (`object` === typeof vTree) {
      const vtree$ = Rx.Observable.just(vTree)
      if (vTree.children && vTree.children.length > 0) {
        return Rx.Observable.combineLatest(
          vtree$,
          ...map(vTree.children, parseTree),
          combineVTreeStreams
        )
      }
      return vtree$
    } else {
      throw new Error(`Unhandled tree value`)
    }
  }
```

I'll gladly submit a PR if you like either of these options.

**Comment by TylorS** [comment]
Yes, I'm actually recently aware of this issue, as I ran into it with motorcycle-dom. The issue I opened is https://github.com/motorcyclejs/motorcycle-dom/issues/9 and the pull request to fix it is https://github.com/motorcyclejs/motorcycle-dom/pull/10. I'm only waiting for a code review and was planning to port it back here afterwards.

**Comment by SkaterDad** [comment]
If I'm reading that PR correctly, the library will just ignore null values?

**Comment by TylorS** [comment]
Yes that's correct

**Comment by TylorS** [comment]
But it should just be the 'children' key that is dismissed.

**Comment by SkaterDad** [comment]
I hadn't encountered any errors when 'children' was undefined, only when one of the array values inside of 'children' was null.

Situations like this:

``` javascript
vTree {
  children: [ 
    { ...valid vnode object...},
    null
  ],
  data: { ... }
}
```

Which resulted from `description` being null in this code.

``` javascript
    h('a.gh-link', {props: {href: html_url}}, [
      h('h1', {}, full_name),
      description,
    ]),
```

**Comment by TylorS** [comment]
Interesting, It seems we've come across 2 seemingly related, but slightly different issues. 

I've come across something like this

``` js
{
 sel: 'div',
 ...,
 children: [
  Observable<{
    ...
    text: 'Hello, world',
    children: undefined
  }>
 ]
}
```

**Comment by TylorS** [comment]
It would be good to find a solution that can solve both issues we've come across.

**Comment by SkaterDad** [comment]
For my own sanity, this is what I would expect to happen in the situation you described:
1. The master vTree object is given to `parseTree`
2. The 'div' is evaluated normally.
3. parseTree sees that the div has children, so it does a map on the array, passing the children into parseTreee.
4. The first `if` statement sees an observable, flapMaps the value out of it, passing it back into parseTree.
5. This child node is handled normally.
6. This line sees an undefined child of that child (grandchild?), and ignores it. `if (vTree.children && vTree.children.length > 0) {`

You're saying this throws an error, though?  Was that only in motorcycle-dom, or have you seen it in cycle-snabbdom as well?

I think the issue I run into needs to be handled as a new part of the parseTree `if...then...` logic.  Or perhaps we should find out why snabbdom isn't handling null values on its own?

**Comment by TylorS** [comment]
To be honest, I haven't used this library since I updated it. It was just a port back from motorcycle-dom. I think the errors come specifically from parseTree rather than snabbdom.

I'm curious as to how adding

``` js
if (!vTree) {
  return null
}
...
filter(x => x !== null)
```

Doesn't solve both of our issues, as it just omits falsey values for ever being rendered, and leaves all of it's siblings alone.
Perhaps

``` js
if (!vTree) {
 return Rx.Observable.just(null)
}
```

would be better, assuming snabbdom doesn't complain about it or render 'null'?

**Comment by TylorS** [comment]
Also I found a bug just now looking at parseTree 
https://github.com/TylorS/cycle-snabbdom/blob/master/src/parseTree.js#L16

observe should be subscribe

**Comment by TylorS** [comment]
I'm going to add some tests and figure this out.

**Comment by TylorS** [comment]
@SkaterDad I think I have a proper fix with this commit https://github.com/TylorS/cycle-snabbdom/commit/e04e3cee1d93cde25cc9af905f86d8420a8c2011. I'll merge it if you don't have any further concerns on it.

In particular, all of these new tests pass
https://github.com/TylorS/cycle-snabbdom/blob/e04e3cee1d93cde25cc9af905f86d8420a8c2011/test/browser/index.js#L111-L205

**Comment by TylorS** [comment]
Note that this didn't work because snabbdom doesn't handle null
I think the exact error was something like `cannot find property data of undefined` 

```
if (!vTree) {
 return Rx.Observable.just(null)
}
```

**Comment by SkaterDad** [comment]
Those updates & tests certainly look good to me.  I'll give them a try once you're push a new release.

It will be nice to not have to wrap potentially null text values in spans or divs!

**Comment by TylorS** [comment]
Also going to push it with auto-scoping that will work with `@cycle/isolate`

**Comment by TylorS** [comment]
npm version 0.4.0 :+1: 
Let me know how it goes

**Comment by SkaterDad** [comment]
Just tried it out, and the update works like a charm.  Thanks!

**Comment by TylorS** [comment]
Great, enjoy :+1:
