### ISSUE TITLE
can not make cycle-snabbdom runable with xstream

### ISSUE THREAD

**Issue by awesomektvn** [TylorS/cycle-snabbdom#31]
it seems that cycle-snabbdom stick strictly with rxjs.

When I try to swap to [xstream](https://github.com/staltz/xstream), It failed with error:

`Uncaught TypeError: observables[_name2].doOnError is not a function`

```
import Cycle from '@cycle/core'
import {modules, makeDOMDriver, h} from 'cycle-snabbdom'
import xs from 'xstream';
const {
  StyleModule, PropsModule,
  AttrsModule, ClassModule,
  HeroModule, EventsModule,
} = modules

const main = () => ({DOM: xs.of(h('div', 'yoyo'))});
Cycle.run(main, {
  DOM: makeDOMDriver('#application', {modules: [
    StyleModule, PropsModule,
    AttrsModule, ClassModule,
    HeroModule, EventsModule
  ]})
})
```

**Comment by TylorS** [comment]
This package will not be receiving too many updates, if any. The official @cycle/dom v10.0.0 is a full write of this package in TypeScript, and is actually written in xstream.

```
npm install --save @cycle/dom@10.0.0-rc21
```
